-- FIX AND SEED DATA FOR ABERDEEN CONSTRUCTION
-- Run this in your Supabase SQL Editor

-- 1. ENSURE COLUMNS EXIST (Fixing "does not exist" errors)
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='company_details' AND column_name='years_experience') THEN
        ALTER TABLE public.company_details ADD COLUMN years_experience text DEFAULT '14+';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='company_details' AND column_name='projects_completed') THEN
        ALTER TABLE public.company_details ADD COLUMN projects_completed text DEFAULT '200+';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='company_details' AND column_name='happy_clients') THEN
        ALTER TABLE public.company_details ADD COLUMN happy_clients text DEFAULT '99%';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='company_details' AND column_name='working_hours') THEN
        ALTER TABLE public.company_details ADD COLUMN working_hours text DEFAULT 'Mon - Fri: 8:00 AM - 6:00 PM';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='company_details' AND column_name='brand_name') THEN
        ALTER TABLE public.company_details ADD COLUMN brand_name text DEFAULT 'Aberdeen';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='company_details' AND column_name='brand_subtitle') THEN
        ALTER TABLE public.company_details ADD COLUMN brand_subtitle text DEFAULT 'Building & Construction';
    END IF;
END $$;

-- 2. ENSURE TABLES EXIST
CREATE TABLE IF NOT EXISTS public.team_members (
    id bigint generated by default as identity primary key,
    name text not null,
    role text not null,
    image text,
    bio text,
    linkedin text,
    twitter text,
    order_index int default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS public.testimonials (
    id bigint generated by default as identity primary key,
    client_name text not null,
    role text,
    content text not null,
    image text,
    rating int default 5,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS public.faqs (
    id bigint generated by default as identity primary key,
    question text not null,
    answer text not null,
    order_index int default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. ENABLE RLS & POLICIES (If tables were just created)
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faqs ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Team') THEN
        CREATE POLICY "Public Read Team" ON public.team_members FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Testimonials') THEN
        CREATE POLICY "Public Read Testimonials" ON public.testimonials FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read FAQs') THEN
        CREATE POLICY "Public Read FAQs" ON public.faqs FOR SELECT USING (true);
    END IF;
    -- Write policies for Demo
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Write Team') THEN
        CREATE POLICY "Public Write Team" ON public.team_members FOR ALL USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Write Testimonials') THEN
        CREATE POLICY "Public Write Testimonials" ON public.testimonials FOR ALL USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Write FAQs') THEN
        CREATE POLICY "Public Write FAQs" ON public.faqs FOR ALL USING (true);
    END IF;
END $$;

-- 4. CLEAN UP AND INSERT DATA
DELETE FROM public.projects;
DELETE FROM public.services;
DELETE FROM public.team_members;
DELETE FROM public.testimonials;
DELETE FROM public.faqs;
DELETE FROM public.company_details;

-- INSERT COMPANY
INSERT INTO public.company_details (id, brand_name, brand_subtitle, phone, email, address, working_hours, years_experience, projects_completed, happy_clients)
VALUES (1, 'Saud Shehatha', 'Construction LLC', '(123) 456-7890', 'info@saudshehatha.com', 'Smart Heights Building, Barsha Heights, Dubai', 'Sun - Thu: 9:00 AM - 5:30 PM', '14+', '200+', '99%');

-- INSERT SERVICES
INSERT INTO public.services (title, icon, description, features)
VALUES 
('Architecture & Planning', 'Layout', 'Bespoke structural design and urban planning for modern Aberdeen developments.', ARRAY['Site Analysis', '3D Modeling', 'Permit Assistance']),
('Commercial Renovations', 'Building2', 'High-end office and retail transformations designed for business growth.', ARRAY['Office Fit-outs', 'Structural Upgrades', 'Interior Design']),
('New Home Construction', 'ShoppingBag', 'Building dream homes with traditional quality and modern sustainability.', ARRAY['Civil Works', 'Roofing', 'Plumbing & Electrical']),
('Kitchen & Bath Remodel', 'Wrench', 'Premium upgrades for your most important home spaces.', ARRAY['Custom Cabinetry', 'Luxury Fittings', 'Tiling']),
('Industrial Facilities', 'Factory', 'Large scale logistics and manufacturing plants with robust engineering.', ARRAY['Steel Structures', 'Heavy Flooring', 'HVAC Systems']),
('Basement Finishing', 'Layout', 'Maximizing your property value with high-quality basement conversions.', ARRAY['Waterproofing', 'Lighting Design', 'Insulation']);

-- INSERT PROJECTS
INSERT INTO public.projects (title, category, location, year, area, description, image)
VALUES 
('Riverside Plaza', 'Commercial', 'Aberdeen Harbor', '2023', '55,000 sq ft', 'State-of-the-art office complex.', 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070'),
('The Granite Villa', 'Residential', 'West End, Aberdeen', '2024', '14,000 sq ft', 'Luxury family home featuring local granite.', 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=2071'),
('Shire Logistics Park', 'Industrial', 'Dyce', '2022', '150,000 sq ft', 'Massive distribution center.', 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=2070');

-- INSERT TEAM
INSERT INTO public.team_members (name, role, image, bio, order_index)
VALUES 
('Thomas Miller', 'Chief Executive Officer', '/images/team_1.png', '15+ years experience in the Aberdeen market.', 1),
('Sarah Mitchell', 'Lead Architect', '/images/team_2.png', 'Specializing in sustainable modern infrastructure.', 2),
('Richard West', 'Operations Director', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=2070', 'Expert in site logistics and management.', 3),
('Emma Rogers', 'Principal Engineer', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=1976', 'Dedicated to precision and safety excellence.', 4);

-- INSERT TESTIMONIALS
INSERT INTO public.testimonials (client_name, role, content, image, rating)
VALUES 
('Alexander Grant', 'Property Developer', 'Aberdeen Construction delivered our project 2 months early. Their attention to structural detail and local building codes is unmatched.', 'https://i.pravatar.cc/150?img=68', 5),
('Fiona Ross', 'Home Owner', 'The kitchen remodel surpassed all our expectations. Truly professional craftsmen who care about the final touch.', 'https://i.pravatar.cc/150?img=44', 5),
('David Sterling', 'CEO, Sterling Logistics', 'A reliable partner for industrial construction. Robust designs and clear communication throughout.', 'https://i.pravatar.cc/150?img=32', 5);

-- INSERT FAQS
INSERT INTO public.faqs (question, answer, order_index)
VALUES 
('Do you handle planning permission?', 'Yes, we have a dediated team that handles all local Aberdeen City and Shire planning applications from start to finish.', 1),
('What is your typical project timeline?', 'Timelines vary by scale, but a standard residential build typically ranges from 6 to 12 months including finishing.', 2),
('Are you fully insured for structural work?', 'Absolutely. We carry comprehensive public liability and professional indemnity insurance for all structural engineering works.', 3),
('Can we visit an active construction site?', 'We can arrange site visits for established clients following strict health and safety protocols.', 4);
