-- SIMPLE TEAM MEMBERS TABLE SETUP
-- Run this in your Supabase SQL Editor

-- 1. Drop existing table if it has issues (CAREFUL: This deletes existing data)
DROP TABLE IF EXISTS public.team_members CASCADE;

-- 2. Create Team Members Table
CREATE TABLE public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  image text not null,
  bio text default '',
  linkedin text default '#',
  twitter text default '#',
  order_index int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable Row Level Security
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies (Allow all operations for now)
CREATE POLICY "Enable read access for all users" ON public.team_members
  FOR SELECT USING (true);

CREATE POLICY "Enable insert access for all users" ON public.team_members
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update access for all users" ON public.team_members
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete access for all users" ON public.team_members
  FOR DELETE USING (true);

-- 5. Insert initial team members
INSERT INTO public.team_members (name, role, image, bio, order_index)
VALUES 
  ('Engr. Saud Shehatha', 'Founder & Chief Executive Officer', '/images/team_1.png', '15+ years experience in the construction industry.', 1),
  ('Engr. Rafeeq', 'Director of Operations', '/images/team_2.png', 'Specialist in high-rise building projects.', 2);
