-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- Create Projects Table
create table public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  location text not null,
  year text not null,
  area text not null,
  description text not null,
  image text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Services Table
create table public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  icon text not null,
  description text not null,
  features text[] default '{}'::text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Company Details Table
create table public.company_details (
  id bigint generated by default as identity primary key,
  brand_name text not null default 'Saud Shehatha',
  brand_subtitle text not null default 'Construction LLC',
  years_experience text not null default '14+',
  projects_completed text not null default '200+',
  happy_clients text not null default '99%',
  phone text not null default '(123) 456-7890',
  email text not null default 'info@saudshehatha.com',
  address text not null default 'Smart Heights Building, Barsha Heights, Dubai',
  working_hours text not null default 'Sun - Thu: 9:00 AM - 5:30 PM',
  facebook text default '#',
  instagram text default '#',
  linkedin text default '#',
  twitter text default '#',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert Default Company Details (Singleton)
insert into public.company_details (id, brand_name, brand_subtitle, phone, email, address, working_hours)
values (1, 'Saud Shehatha', 'Construction LLC', '(123) 456-7890', 'info@saudshehatha.com', 'Smart Heights Building, Barsha Heights, Dubai', 'Sun - Thu: 9:00 AM - 5:30 PM')
on conflict (id) do nothing;

-- Enable Row Level Security (RLS)
alter table public.projects enable row level security;
alter table public.services enable row level security;
alter table public.company_details enable row level security;

-- Create Policy: Allow public read access to all tables
create policy "Public Read Projects" on public.projects for select using (true);
create policy "Public Read Services" on public.services for select using (true);
create policy "Public Read Company Details" on public.company_details for select using (true);

-- Create Policy: Allow authenticated (admin) write access
-- Note: You need to set up authentication or just allow public write for now if debugging, 
-- but for security we usually restrict this. For this demo, we'll allow anon write 
-- ONLY IF you plan to use the admin panel without full auth implementation yet.
-- Ideally: create policy "Admin Write" on ... for all using (auth.role() = 'authenticated');
-- For now, allowing all creates/updates for simplicity as requested by "connect backend". 
-- WARNING: This is insecure for production.
create policy "Public Write Projects" on public.projects for insert with check (true);
create policy "Public Update Projects" on public.projects for update using (true);
create policy "Public Delete Projects" on public.projects for delete using (true);

create policy "Public Write Services" on public.services for insert with check (true);
create policy "Public Update Services" on public.services for update using (true);
create policy "Public Delete Services" on public.services for delete using (true);

create policy "Public Update Company" on public.company_details for update using (true);
