-- ENHANCED SCHEMA UPDATE
-- Adds Team Members, Testimonials, and FAQs to the dynamic admin panel

-- 1. Create Services Table (Updated)
CREATE TABLE IF NOT EXISTS public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  icon text not null,
  description text not null,
  features text[],
  document_url text, -- New field
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1. Create Team Members Table
CREATE TABLE IF NOT EXISTS public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  image text not null,
  bio text,
  linkedin text default '#',
  twitter text default '#',
  order_index int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Testimonials Table
CREATE TABLE IF NOT EXISTS public.testimonials (
  id bigint generated by default as identity primary key,
  client_name text not null,
  role text,
  content text not null,
  image text not null,
  rating int default 5,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create FAQs Table
CREATE TABLE IF NOT EXISTS public.faqs (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  order_index int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable RLS
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faqs ENABLE ROW LEVEL SECURITY;

-- 5. Policies (Safe check)
DO $$ 
BEGIN
    -- Team Members Policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Team') THEN
        CREATE POLICY "Public Read Team" ON public.team_members FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admin Write Team') THEN
        CREATE POLICY "Admin Write Team" ON public.team_members FOR ALL USING (true);
    END IF;

    -- Testimonials Policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Testimonials') THEN
        CREATE POLICY "Public Read Testimonials" ON public.testimonials FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admin Write Testimonials') THEN
        CREATE POLICY "Admin Write Testimonials" ON public.testimonials FOR ALL USING (true);
    END IF;

    -- FAQs Policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read FAQs') THEN
        CREATE POLICY "Public Read FAQs" ON public.faqs FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admin Write FAQs') THEN
        CREATE POLICY "Admin Write FAQs" ON public.faqs FOR ALL USING (true);
    END IF;
END $$;

-- 6. Dummy Data Seeding (Matching the User's Image and Request)

-- Dummy Services
INSERT INTO public.services (title, icon, description, features, document_url)
VALUES 
('Civil Engineering', 'Building2', 'Structural design and analysis for large-scale infrastructure projects including bridges and highways.', ARRAY['Site Analysis', 'Structural Design', 'Project Oversight'], 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'),
('Residential Construction', 'Home', 'Bespoke luxury villa construction and residential developments in key Dubai locations.', ARRAY['Custom Design', 'Premium Finish', 'Turnkey Delivery'], 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'),
('Industrial Facilities', 'Factory', 'Specialized construction for logistics hubs, factories, and heavy industrial plants.', ARRAY['Robust Infrastructure', 'Safety Certification', 'Logistics Planning'], 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'),
('Project Management', 'Layout', 'Full-cycle management from planning through execution to ensure on-time delivery.', ARRAY['Cost Control', 'Scheduling', 'Quality Assurance'], 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'),
('Commercial Renovation', 'ShoppingBag', 'State-of-the-art office and retail space fit-outs and comprehensive structural renovations.', ARRAY['Modern Design', 'Speedy Execution', 'Retail Standards'], 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf')
ON CONFLICT (id) DO NOTHING;

-- Dummy Projects (Matching the High-End Look in Image)
INSERT INTO public.projects (title, category, location, year, area, description, image)
VALUES 
('Marina View Residence', 'Residential', 'Dubai Marina', '2023', '45,000 sq ft', 'A high-rise residential complex featuring state-of-the-art amenities and premium waterfront views.', 'https://images.unsplash.com/photo-1545324418-f1d3c59cd473?q=80&w=1948&auto=format&fit=crop'),
('Al Jurf Logistics Hub', 'Industrial', 'Ajman', '2022', '120,000 sq ft', 'Massive logistics facility designed for heavy commerce and efficient regional distribution.', 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=2070'),
('The Downtown Plaza', 'Commercial', 'Business Bay, Dubai', '2024', '15,000 sq ft', 'Modern collaborative workspace and retail development in the heart of the business district.', 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=2069'),
('Palm Jumeirah Villa', 'Luxury', 'Palm Jumeirah', '2023', '12,000 sq ft', 'A custom-built luxury villa with private beach access and cutting-edge home automation.', 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=2071')
ON CONFLICT (id) DO NOTHING;

-- Dummy Team Members (From the Image)
INSERT INTO public.team_members (name, role, image, bio)
VALUES 
('Thomas Miller', 'Chief Executive Officer', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1974&auto=format&fit=crop', '15+ years leading major construction projects across the Middle East.'),
('Sarah Mitchell', 'Lead Architect', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=1974&auto=format&fit=crop', 'Visionary designer specializing in sustainable modern infrastructure.'),
('Richard West', 'Operations Director', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=2070&auto=format&fit=crop', 'Expert in logistics and site management for complex developments.'),
('Emma Rogers', 'Principal Engineer', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=1976&auto=format&fit=crop', 'Structural specialist dedicated to precision and safety excellence.')
ON CONFLICT (id) DO NOTHING;

-- Dummy Testimonials
INSERT INTO public.testimonials (client_name, role, content, image, rating)
VALUES 
('James Wilson', 'SVP at Global Logistics', 'Saud Shehatha delivered our warehouse facility 2 months ahead of schedule. Their attention to detail in the steel structure was impeccable.', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=1974', 5),
('Al Reem Property Group', 'Developer', 'Working with their construction division has been a seamless experience. They understand the luxury market in Dubai perfectly.', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=2070', 5)
ON CONFLICT (id) DO NOTHING;

