-- TEAM MEMBERS & NEW COLUMNS UPDATE SCRIPT
-- Paste this into your Supabase SQL Editor to enable Team Management and fix missing columns.

-- 1. Create Team Members Table
CREATE TABLE IF NOT EXISTS public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  image text not null,
  bio text default '',
  linkedin text default '#',
  twitter text default '#',
  order_index int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Add Missing Columns to existing tables (if they don't exist)
DO $$ 
BEGIN
    -- Add service_type to quotes
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='quotes' AND column_name='service_type') THEN
        ALTER TABLE public.quotes ADD COLUMN service_type text;
    END IF;

    -- Add document_url to services
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='services' AND column_name='document_url') THEN
        ALTER TABLE public.services ADD COLUMN document_url text default '';
    END IF;
END $$;

-- 3. Enable RLS and Policies for Team Members
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Team') THEN
        CREATE POLICY "Public Read Team" ON public.team_members FOR SELECT USING (true);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Insert Team') THEN
        CREATE POLICY "Public Insert Team" ON public.team_members FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Update Team') THEN
        CREATE POLICY "Public Update Team" ON public.team_members FOR UPDATE USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Delete Team') THEN
        CREATE POLICY "Public Delete Team" ON public.team_members FOR DELETE USING (true);
    END IF;
END $$;

-- 4. Initial Seed for Sample Team (Optional)
INSERT INTO public.team_members (name, role, image, bio, order_index)
VALUES 
('Engr. Saud Shehatha', 'Founder & Chief executive officer', '/images/team_1.png', '15+ years experience in the construction industry.', 1),
('Engr. Rafeeq', 'Director of Operations', '/images/team_2.png', 'Specialist in high-rise building projects.', 2)
ON CONFLICT (id) DO NOTHING;
