-- SAFE SCHEMA UPDATE SCRIPT
-- This script uses "IF NOT EXISTS" to avoid errors if you run it multiple times.

-- 1. Create Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  location text not null,
  year text not null,
  area text not null,
  description text not null,
  image text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Services Table
CREATE TABLE IF NOT EXISTS public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  icon text not null,
  description text not null,
  features text[] default '{}'::text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Company Details Table
CREATE TABLE IF NOT EXISTS public.company_details (
  id bigint generated by default as identity primary key,
  brand_name text not null default 'Saud Shehatha',
  brand_subtitle text not null default 'Construction LLC',
  phone text not null default '(123) 456-7890',
  email text not null default 'info@saudshehatha.com',
  address text not null default 'Smart Heights Building, Barsha Heights, Dubai',
  working_hours text not null default 'Sun - Thu: 9:00 AM - 5:30 PM',
  facebook text default '#',
  instagram text default '#',
  linkedin text default '#',
  twitter text default '#',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Initial seed for Company Details (if not present)
INSERT INTO public.company_details (id, brand_name, brand_subtitle, phone, email, address, working_hours)
VALUES (1, 'Saud Shehatha', 'Construction LLC', '(123) 456-7890', 'info@saudshehatha.com', 'Smart Heights Building, Barsha Heights, Dubai', 'Sun - Thu: 9:00 AM - 5:30 PM')
ON CONFLICT (id) DO NOTHING;

-- 5. Enable RLS (Safe to run multiple times)
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_details ENABLE ROW LEVEL SECURITY;

-- 6. Policies (Use DO blocks to avoid "already exists" errors)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Projects') THEN
        CREATE POLICY "Public Read Projects" ON public.projects FOR SELECT USING (true);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Write Projects') THEN
        CREATE POLICY "Public Write Projects" ON public.projects FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Update Projects') THEN
        CREATE POLICY "Public Update Projects" ON public.projects FOR UPDATE USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Delete Projects') THEN
        CREATE POLICY "Public Delete Projects" ON public.projects FOR DELETE USING (true);
    END IF;

    -- Services Policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Services') THEN
        CREATE POLICY "Public Read Services" ON public.services FOR SELECT USING (true);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Write Services') THEN
        CREATE POLICY "Public Write Services" ON public.services FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Update Services') THEN
        CREATE POLICY "Public Update Services" ON public.services FOR UPDATE USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Delete Services') THEN
        CREATE POLICY "Public Delete Services" ON public.services FOR DELETE USING (true);
    END IF;

    -- Company Details Policy
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Company Details') THEN
        CREATE POLICY "Public Read Company Details" ON public.company_details FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Update Company') THEN
        CREATE POLICY "Public Update Company" ON public.company_details FOR UPDATE USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Insert Company') THEN
        CREATE POLICY "Public Insert Company" ON public.company_details FOR INSERT WITH CHECK (true);
    END IF;

    -- 7. Create Quotes/Messages Table
    CREATE TABLE IF NOT EXISTS public.quotes (
      id bigint generated by default as identity primary key,
      name text not null,
      email text not null,
      phone text,
      message text not null,
      status text not null default 'pending', -- pending, reviewed, contacted
      created_at timestamp with time zone default timezone('utc'::text, now()) not null
    );

    -- Enable RLS for quotes
    ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;

    -- Quotes Policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Insert Quotes') THEN
        CREATE POLICY "Public Insert Quotes" ON public.quotes FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Quotes') THEN
        CREATE POLICY "Public Read Quotes" ON public.quotes FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Update Quotes') THEN
        CREATE POLICY "Public Update Quotes" ON public.quotes FOR UPDATE USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Delete Quotes') THEN
        CREATE POLICY "Public Delete Quotes" ON public.quotes FOR DELETE USING (true);
    END IF;
END $$;
