-- COMPLETE SUPABASE SCHEMA & UPDATE SCRIPT
-- This script contains ALL tables and security policies for the Trustworthy Builds project.
-- Run this in your Supabase SQL Editor.

-- 1. Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  location text not null,
  year text not null,
  area text not null,
  description text not null,
  image text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Services Table
CREATE TABLE IF NOT EXISTS public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  icon text not null,
  description text not null,
  features text[] default '{}'::text[],
  document_url text default '',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Company Details Table
CREATE TABLE IF NOT EXISTS public.company_details (
  id bigint generated by default as identity primary key,
  brand_name text not null default 'Saud Shehatha',
  brand_subtitle text not null default 'Construction LLC',
  phone text not null default '0527267426',
  email text not null default 'Saudshehathaconstrion@gmail.com',
  address text not null default 'SMart Heights Tower, No: 707, Barsha Heights, Dubai',
  working_hours text not null default 'Sun - Thu: 9:00 AM - 5:30 PM',
  facebook text default '#',
  instagram text default '#',
  linkedin text default '#',
  twitter text default '#',
  years_experience text default '14+',
  projects_completed text default '200+',
  happy_clients text default '99%',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Team Members Table
CREATE TABLE IF NOT EXISTS public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  image text not null,
  bio text default '',
  linkedin text default '#',
  twitter text default '#',
  order_index int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Quotes/Messages Table
CREATE TABLE IF NOT EXISTS public.quotes (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  service_type text,
  message text not null,
  status text not null default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Testimonials (Optional but good to have)
CREATE TABLE IF NOT EXISTS public.testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  content text not null,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. FAQs
CREATE TABLE IF NOT EXISTS public.faqs (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  order_index int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Initial seed for Company Details (ID 1)
INSERT INTO public.company_details (id, brand_name, brand_subtitle, phone, email, address, working_hours)
VALUES (1, 'Saud Shehatha', 'Construction LLC', '0527267426', 'Saudshehathaconstrion@gmail.com', 'SMart Heights Tower, No: 707, Barsha Heights, Dubai', 'Sun - Thu: 9:00 AM - 5:30 PM')
ON CONFLICT (id) DO UPDATE SET
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  address = EXCLUDED.address;

-- ENABLE RLS ON ALL TABLES
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faqs ENABLE ROW LEVEL SECURITY;

-- UNIVERSAL PUBLIC ACCESS POLICIES (Read/Write for simplicity)
-- In production, you would restrict Write/Update/Delete to authenticated users.

DO $$ 
DECLARE
    t text;
BEGIN
    FOR t IN SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' 
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Public Read %I" ON public.%I', t, t);
        EXECUTE format('CREATE POLICY "Public Read %I" ON public.%I FOR SELECT USING (true)', t, t);
        
        EXECUTE format('DROP POLICY IF EXISTS "Public Write %I" ON public.%I', t, t);
        EXECUTE format('CREATE POLICY "Public Write %I" ON public.%I FOR INSERT WITH CHECK (true)', t, t);
        
        EXECUTE format('DROP POLICY IF EXISTS "Public Update %I" ON public.%I', t, t);
        EXECUTE format('CREATE POLICY "Public Update %I" ON public.%I FOR UPDATE USING (true)', t, t);
        
        EXECUTE format('DROP POLICY IF EXISTS "Public Delete %I" ON public.%I', t, t);
        EXECUTE format('CREATE POLICY "Public Delete %I" ON public.%I FOR DELETE USING (true)', t, t);
    END LOOP;
END $$;
